const myTypes = {
    FETCH_ARTICLES_REQUEST: 'FETCH_ARTICLES_REQUEST',
    FETCH_ARTICLES_SUSSESS: 'FETCH_ARTICLES_SUCCESS',
    FETCH_ARTICLE_FAILURE: 'FETCH_ARTICLES_FAILURE',
    FETCH_ARTICLES:'FETCH_ARTICLES',
    UPDATE_NEWS_CURRENT_INDE: 'UPDATE_NEWS_CURRENT_INDEX'
}

export default myTypes;